In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

df = pd.read_csv("healthcare_dataset.csv")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (55500, 15)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [4]:
df.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [5]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(534)

In [7]:
for column in df.columns:
    print("\n", column)
    print(df[column].nunique())

 Name
49992

 Age
77

 Gender
2

 Blood Type
8

 Medical Condition
6

 Date of Admission
1827

 Doctor
40341

 Hospital
39876

 Insurance Provider
5

 Billing Amount
50000

 Room Number
400

 Admission Type
3

 Discharge Date
1856

 Medication
5

 Test Results
3

In [8]:
print("Gender:", df["Gender"].unique())
print("Medical Conditions:", df["Medical Condition"].unique())
print("Admission Types:", df["Admission Type"].unique())
print("Test Results:", df["Test Results"].unique())
print("Medications:", df["Medication"].unique())

Gender: ['Male' 'Female']
Medical Conditions: ['Cancer' 'Obesity' 'Diabetes' 'Asthma' 'Hypertension' 'Arthritis']
Admission Types: ['Urgent' 'Emergency' 'Elective']
Test Results: ['Normal' 'Inconclusive' 'Abnormal']
Medications: ['Paracetamol' 'Ibuprofen' 'Aspirin' 'Penicillin' 'Lipitor']

In [9]:
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])

print(df[["Date of Admission", "Discharge Date"]].dtypes)

Date of Admission    datetime64[ns]
Discharge Date       datetime64[ns]
dtype: object

In [10]:
print("Invalid ages:", ((df["Age"] < 0) | (df["Age"] > 120)).sum())

print("Negative billing:", (df["Billing Amount"] < 0).sum())

Invalid ages: 0
Negative billing: 108

In [11]:
df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (54966, 15)

In [12]:
missing = df.isnull().sum()

print(missing)

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [13]:
df.columns = [
    "Patient_Name",
    "Age",
    "Gender",
    "Blood_Type",
    "Medical_Condition",
    "Admission_Date",
    "Doctor",
    "Hospital",
    "Insurance_Provider",
    "Billing_Amount",
    "Room_Number",
    "Admission_Type",
    "Discharge_Date",
    "Medication",
    "Test_Results"
]

print(df.columns)

Index(['Patient_Name', 'Age', 'Gender', 'Blood_Type', 'Medical_Condition',
       'Admission_Date', 'Doctor', 'Hospital', 'Insurance_Provider',
       'Billing_Amount', 'Room_Number', 'Admission_Type', 'Discharge_Date',
       'Medication', 'Test_Results'],
      dtype='object')

In [14]:
df["Admission_Date"] = pd.to_datetime(
    df["Admission_Date"],
    errors="coerce"
)

df["Discharge_Date"] = pd.to_datetime(
    df["Discharge_Date"],
    errors="coerce"
)

In [15]:
print(df[["Admission_Date", "Discharge_Date"]].dtypes)

Admission_Date    datetime64[ns]
Discharge_Date    datetime64[ns]
dtype: object

In [16]:
df["Length_of_Stay"] = (
    df["Discharge_Date"] - df["Admission_Date"]
).dt.days

In [17]:
print(df["Length_of_Stay"].describe())

count    54966.000000
mean        15.499290
std          8.661471
min          1.000000
25%          8.000000
50%         15.000000
75%         23.000000
max         30.000000
Name: Length_of_Stay, dtype: float64

In [18]:
print(
    "Invalid Length of Stay:",
    (df["Length_of_Stay"] < 0).sum()
)

Invalid Length of Stay: 0

In [19]:
bins = [0, 18, 30, 45, 60, 75, 120]

labels = [
    "0-18",
    "19-30",
    "31-45",
    "46-60",
    "61-75",
    "76+"
]

df["Age_Group"] = pd.cut(
    df["Age"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

In [20]:
df["Age_Group"].value_counts().sort_index()

Age_Group
0-18       886
19-30     9519
31-45    12116
46-60    12273
61-75    12098
76+       8074
Name: count, dtype: int64

In [21]:
print("Invalid ages:", ((df["Age"] < 0) | (df["Age"] > 120)).sum())

Invalid ages: 0

In [22]:
categorical_columns = [
    "Gender",
    "Blood_Type",
    "Medical_Condition",
    "Doctor",
    "Hospital",
    "Insurance_Provider",
    "Admission_Type",
    "Medication",
    "Test_Results"
]

for column in categorical_columns:
    df[column] = (
        df[column]
        .astype(str)
        .str.strip()
    )

In [23]:
print("Gender:", df["Gender"].unique())

print("Medical Conditions:",
      df["Medical_Condition"].unique())

print("Admission Types:",
      df["Admission_Type"].unique())

print("Test Results:",
      df["Test_Results"].unique())

Gender: ['Male' 'Female']
Medical Conditions: ['Cancer' 'Obesity' 'Diabetes' 'Asthma' 'Hypertension' 'Arthritis']
Admission Types: ['Urgent' 'Emergency' 'Elective']
Test Results: ['Normal' 'Inconclusive' 'Abnormal']

In [24]:
df["Recovery_Flag"] = np.where(
    df["Test_Results"] == "Normal",
    1,
    0
)

In [25]:
print(
    df["Recovery_Flag"].value_counts()
)

Recovery_Flag
0    36635
1    18331
Name: count, dtype: int64

In [26]:
recovery_rate = (
    df["Recovery_Flag"].mean() * 100
)

print(
    "Recovery Rate:",
    round(recovery_rate, 2),
    "%"
)

Recovery Rate: 33.35 %

In [27]:
df["Admission_Year"] = (
    df["Admission_Date"].dt.year
)

df["Admission_Month"] = (
    df["Admission_Date"].dt.month
)

df["Admission_Month_Name"] = (
    df["Admission_Date"].dt.strftime("%B")
)

df["Admission_Year_Month"] = (
    df["Admission_Date"]
    .dt.to_period("M")
    .astype(str)
)

In [28]:
print(
    "Missing billing:",
    df["Billing_Amount"].isnull().sum()
)

Missing billing: 0

In [29]:
print(
    "Negative billing:",
    (df["Billing_Amount"] < 0).sum()
)

Negative billing: 106

In [30]:
print(
    df["Billing_Amount"].describe()
)

count    54966.000000
mean     25544.306284
std      14208.409711
min      -2008.492140
25%      13243.718641
50%      25542.749145
75%      37819.858159
max      52764.276736
Name: Billing_Amount, dtype: float64

In [31]:
print("Final shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:",
      df.duplicated().sum())

print("\nRecovery Flag:")
print(df["Recovery_Flag"].value_counts())

Final shape: (54966, 22)

Missing values:
Patient_Name            0
Age                     0
Gender                  0
Blood_Type              0
Medical_Condition       0
Admission_Date          0
Doctor                  0
Hospital                0
Insurance_Provider      0
Billing_Amount          0
Room_Number             0
Admission_Type          0
Discharge_Date          0
Medication              0
Test_Results            0
Length_of_Stay          0
Age_Group               0
Recovery_Flag           0
Admission_Year          0
Admission_Month         0
Admission_Month_Name    0
Admission_Year_Month    0
dtype: int64

Duplicate rows: 0

Recovery Flag:
Recovery_Flag
0    36635
1    18331
Name: count, dtype: int64

In [32]:
df["Patient_Name"] = (
    df["Patient_Name"]
    .astype(str)
    .str.strip()
    .str.title()
)
print(df["Patient_Name"].head(20))

0           Bobby Jackson
1            Leslie Terry
2             Danny Smith
3            Andrew Watts
4           Adrienne Bell
5           Emily Johnson
6          Edward Edwards
7      Christina Martinez
8         Jasmine Aguilar
9        Christopher Berg
10       Michelle Daniels
11         Aaron Martinez
12          Connor Hansen
13           Robert Bauer
14           Brooke Brady
15     Ms. Natalie Gamble
16          Haley Perkins
17    Mrs. Jamie Campbell
18           Luke Burgess
19         Daniel Schmidt
Name: Patient_Name, dtype: object

In [33]:
print("Unique patient names:", df["Patient_Name"].nunique())

Unique patient names: 40235

In [34]:
negative_billing = df[df["Billing_Amount"] < 0]

print("Negative billing records:", len(negative_billing))

Negative billing records: 106

In [35]:
negative_billing[[
    "Patient_Name",
    "Billing_Amount",
    "Medical_Condition",
    "Hospital"
]].head(10)

,Patient_Name,Billing_Amount,Medical_Condition,Hospital
132,Ashley Erickson,-502.507813,Cancer,"and Johnson Moore, Branch"
799,Christopher Weiss,-1018.245371,Asthma,Hunter-Hughes
1018,Ashley Warner,-306.364925,Hypertension,"and Wagner, Lee Klein"
1421,Jay Galloway,-109.097122,Asthma,Group Peters
2103,Joshua Williamson,-576.727907,Diabetes,"and Huff Reeves, Dennis"
2696,Scott Vazquez,-135.986000,Diabetes,James Ltd
2855,Carol Anderson,-370.983674,Hypertension,"Carter Carter, and Patterson"
3772,Mr. Christopher Alvarado,-1310.272895,Obesity,Johnson Inc
5445,Alexandra Khan,-692.408820,Arthritis,"Bowen Lopez, and Terry"
5708,Joseph Cox,-353.865186,Diabetes,Inc Ward

In [36]:
negative_billing_percentage = (
    len(negative_billing) / len(df) * 100
)

print(
    f"Negative billing percentage: "
    f"{negative_billing_percentage:.2f}%"
)

Negative billing percentage: 0.19%

In [37]:
df = df[df["Billing_Amount"] >= 0].copy()

print("Records after removing invalid billing values:", len(df))

Records after removing invalid billing values: 54860

In [38]:
df.head()

,Patient_Name,Age,Gender,Blood_Type,Medical_Condition,Admission_Date,Doctor,Hospital,Insurance_Provider,Billing_Amount,Room_Number,Admission_Type,Discharge_Date,Medication,Test_Results,Length_of_Stay,Age_Group,Recovery_Flag,Admission_Year,Admission_Month,Admission_Month_Name,Admission_Year_Month
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2,19-30,1,2024,1,January,2024-01
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6,61-75,0,2019,8,August,2019-08
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15,76+,1,2022,9,September,2022-09
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30,19-30,0,2020,11,November,2020-11
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20,31-45,0,2022,9,September,2022-09

In [39]:
df.to_csv("healthcare_cleaned.csv",index=False)
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!